export const TOURNAMENT_CHAMPION_SEEDS = {
  'internacional-libertadores': [
    { season: '2025', championName: 'Flamengo', runnerUpName: 'Palmeiras', finalScore: '1-0', venue: 'Lima, Peru' },
    { season: '2024', championName: 'Botafogo', runnerUpName: 'Atletico Mineiro', finalScore: '3-1', venue: 'Buenos Aires, Argentina' },
    { season: '2023', championName: 'Fluminense', runnerUpName: 'Boca Juniors', finalScore: '2-1 (a.e.t.)', venue: 'Rio de Janeiro, Brasil' },
    { season: '2022', championName: 'Flamengo', runnerUpName: 'Athletico Paranaense', finalScore: '1-0', venue: 'Guayaquil, Ecuador' },
    { season: '2021', championName: 'Palmeiras', runnerUpName: 'Flamengo', finalScore: '2-1 (a.e.t.)', venue: 'Montevideo, Uruguay' },
    { season: '2020', championName: 'Palmeiras', runnerUpName: 'Santos', finalScore: '1-0', venue: 'Rio de Janeiro, Brasil' },
    { season: '2019', championName: 'Flamengo', runnerUpName: 'River Plate', finalScore: '2-1', venue: 'Lima, Peru' },
    { season: '2018', championName: 'River Plate', runnerUpName: 'Boca Juniors', finalScore: '5-3 agg.', venue: 'Buenos Aires / Madrid' },
    { season: '2017', championName: 'Gremio', runnerUpName: 'Lanus', finalScore: '3-1 agg.', venue: null },
    { season: '2016', championName: 'Atletico Nacional', runnerUpName: 'Independiente del Valle', finalScore: '2-1 agg.', venue: null },
    { season: '2015', championName: 'River Plate', runnerUpName: 'UANL', finalScore: '3-0 agg.', venue: null },
    { season: '2014', championName: 'San Lorenzo', runnerUpName: 'Nacional', finalScore: '2-1 agg.', venue: null },
    { season: '2013', championName: 'Atletico Mineiro', runnerUpName: 'Olimpia', finalScore: '2-2 (4-3 pen.)', venue: null },
    { season: '2012', championName: 'Corinthians', runnerUpName: 'Boca Juniors', finalScore: '3-1 agg.', venue: null },
    { season: '2011', championName: 'Santos', runnerUpName: 'Penarol', finalScore: '2-1 agg.', venue: null },
    { season: '2010', championName: 'Internacional', runnerUpName: 'Guadalajara', finalScore: '5-3 agg.', venue: null },
    { season: '2009', championName: 'Estudiantes', runnerUpName: 'Cruzeiro', finalScore: '2-1 agg.', venue: null },
    { season: '2008', championName: 'Liga de Quito', runnerUpName: 'Fluminense', finalScore: '5-5 (3-1 pen.)', venue: null },
    { season: '2007', championName: 'Boca Juniors', runnerUpName: 'Gremio', finalScore: '5-0 agg.', venue: null },
    { season: '2006', championName: 'Internacional', runnerUpName: 'Sao Paulo', finalScore: '4-3 agg.', venue: null },
    { season: '2005', championName: 'Sao Paulo', runnerUpName: 'Athletico Paranaense', finalScore: '5-1 agg.', venue: null },
    { season: '2004', championName: 'Once Caldas', runnerUpName: 'Boca Juniors', finalScore: '1-1 (2-0 pen.)', venue: null },
    { season: '2003', championName: 'Boca Juniors', runnerUpName: 'Santos', finalScore: '5-1 agg.', venue: null },
    { season: '2002', championName: 'Olimpia', runnerUpName: 'Sao Caetano', finalScore: '2-2 (4-2 pen.)', venue: null },
    { season: '2001', championName: 'Boca Juniors', runnerUpName: 'Cruz Azul', finalScore: '1-1 (3-1 pen.)', venue: null },
    { season: '2000', championName: 'Boca Juniors', runnerUpName: 'Palmeiras', finalScore: '2-2 (4-2 pen.)', venue: null },
    { season: '1999', championName: 'Palmeiras', runnerUpName: 'Deportivo Cali', finalScore: '2-2 (4-3 pen.)', venue: null },
    { season: '1998', championName: 'Vasco da Gama', runnerUpName: 'Barcelona SC', finalScore: '4-1 agg.', venue: null },
    { season: '1997', championName: 'Cruzeiro', runnerUpName: 'Sporting Cristal', finalScore: '1-0 agg.', venue: null },
    { season: '1996', championName: 'River Plate', runnerUpName: 'America de Cali', finalScore: '2-1 agg.', venue: null },
    { season: '1995', championName: 'Gremio', runnerUpName: 'Atletico Nacional', finalScore: '4-2 agg.', venue: null },
    { season: '1994', championName: 'Velez Sarsfield', runnerUpName: 'Sao Paulo', finalScore: '1-1 (5-3 pen.)', venue: null },
    { season: '1993', championName: 'Sao Paulo', runnerUpName: 'Universidad Catolica', finalScore: '5-3 agg.', venue: null },
    { season: '1992', championName: 'Sao Paulo', runnerUpName: "Newell's Old Boys", finalScore: '1-1 (3-2 pen.)', venue: null },
    { season: '1991', championName: 'Colo-Colo', runnerUpName: 'Olimpia', finalScore: '3-0 agg.', venue: null },
    { season: '1990', championName: 'Olimpia', runnerUpName: 'Barcelona SC', finalScore: '3-1 agg.', venue: null },
    { season: '1989', championName: 'Atletico Nacional', runnerUpName: 'Olimpia', finalScore: '2-2 (5-4 pen.)', venue: null },
    { season: '1988', championName: 'Nacional', runnerUpName: "Newell's Old Boys", finalScore: '3-1 agg.', venue: null },
    { season: '1987', championName: 'Penarol', runnerUpName: 'America de Cali', finalScore: '1-0 playoff', venue: null },
    { season: '1986', championName: 'River Plate', runnerUpName: 'America de Cali', finalScore: '3-1 agg.', venue: null },
    { season: '1985', championName: 'Argentinos Juniors', runnerUpName: 'America de Cali', finalScore: '2-2 (5-4 pen.)', venue: null },
    { season: '1984', championName: 'Independiente', runnerUpName: 'Gremio', finalScore: '1-0 agg.', venue: null },
    { season: '1983', championName: 'Gremio', runnerUpName: 'Penarol', finalScore: '3-2 agg.', venue: null },
    { season: '1982', championName: 'Penarol', runnerUpName: 'Cobreloa', finalScore: '1-0 agg.', venue: null },
    { season: '1981', championName: 'Flamengo', runnerUpName: 'Cobreloa', finalScore: '2-0 playoff', venue: null },
    { season: '1980', championName: 'Nacional', runnerUpName: 'Internacional', finalScore: '1-0 agg.', venue: null },
    { season: '1979', championName: 'Olimpia', runnerUpName: 'Boca Juniors', finalScore: '2-0 agg.', venue: null },
    { season: '1978', championName: 'Boca Juniors', runnerUpName: 'Deportivo Cali', finalScore: '4-0 agg.', venue: null },
    { season: '1977', championName: 'Boca Juniors', runnerUpName: 'Cruzeiro', finalScore: '1-1 (5-4 pen.)', venue: null },
    { season: '1976', championName: 'Cruzeiro', runnerUpName: 'River Plate', finalScore: '3-2 playoff', venue: null },
    { season: '1975', championName: 'Independiente', runnerUpName: 'Union Espanola', finalScore: '2-0 playoff', venue: null },
    { season: '1974', championName: 'Independiente', runnerUpName: 'Sao Paulo', finalScore: '1-0 playoff', venue: null },
    { season: '1973', championName: 'Independiente', runnerUpName: 'Colo-Colo', finalScore: '2-1 playoff', venue: null },
    { season: '1972', championName: 'Independiente', runnerUpName: 'Universitario', finalScore: '2-1 agg.', venue: null },
    { season: '1971', championName: 'Nacional', runnerUpName: 'Estudiantes', finalScore: '2-0 playoff', venue: null },
    { season: '1970', championName: 'Estudiantes', runnerUpName: 'Penarol', finalScore: '1-0 agg.', venue: null },
    { season: '1969', championName: 'Estudiantes', runnerUpName: 'Nacional', finalScore: '3-0 agg.', venue: null },
    { season: '1968', championName: 'Estudiantes', runnerUpName: 'Palmeiras', finalScore: '2-0 playoff', venue: null },
    { season: '1967', championName: 'Racing Club', runnerUpName: 'Nacional', finalScore: '2-1 playoff', venue: null },
    { season: '1966', championName: 'Penarol', runnerUpName: 'River Plate', finalScore: '4-2 playoff', venue: null },
    { season: '1965', championName: 'Independiente', runnerUpName: 'Penarol', finalScore: '4-1 playoff', venue: null },
    { season: '1964', championName: 'Independiente', runnerUpName: 'Nacional', finalScore: '1-0 agg.', venue: null },
    { season: '1963', championName: 'Santos', runnerUpName: 'Boca Juniors', finalScore: '5-3 agg.', venue: null },
    { season: '1962', championName: 'Santos', runnerUpName: 'Penarol', finalScore: '3-0 playoff', venue: null },
    { season: '1961', championName: 'Penarol', runnerUpName: 'Palmeiras', finalScore: '2-1 agg.', venue: null },
    { season: '1960', championName: 'Penarol', runnerUpName: 'Olimpia', finalScore: '2-1 agg.', venue: null },
  ],
  'internacional-sudamericana': [
    { season: '2025', championName: 'Lanus', runnerUpName: 'Atletico Mineiro', finalScore: '0-0 (5-4 pen.)', venue: 'Asunción, Paraguay' },
    { season: '2024', championName: 'Racing Club', runnerUpName: 'Cruzeiro', finalScore: '3-1', venue: 'Asunción, Paraguay' },
    { season: '2023', championName: 'Liga de Quito', runnerUpName: 'Fortaleza', finalScore: '1-1 (4-3 pen.)', venue: 'Punta del Este, Uruguay' },
    { season: '2022', championName: 'Independiente del Valle', runnerUpName: 'Sao Paulo', finalScore: '2-0', venue: 'Córdoba, Argentina' },
    { season: '2021', championName: 'Athletico Paranaense', runnerUpName: 'Red Bull Bragantino', finalScore: '1-0', venue: 'Montevideo, Uruguay' },
    { season: '2020', championName: 'Defensa y Justicia', runnerUpName: 'Lanus', finalScore: '3-0', venue: 'Córdoba, Argentina' },
    { season: '2019', championName: 'Independiente del Valle', runnerUpName: 'Colon', finalScore: '3-1', venue: 'Asunción, Paraguay' },
    { season: '2018', championName: 'Athletico Paranaense', runnerUpName: 'Junior', finalScore: '2-2 (4-3 pen.)', venue: null },
    { season: '2017', championName: 'Independiente', runnerUpName: 'Flamengo', finalScore: '3-2 agg.', venue: null },
    { season: '2016', championName: 'Chapecoense', runnerUpName: 'Atletico Nacional', finalScore: 'Titulo otorgado por CONMEBOL', venue: null },
    { season: '2015', championName: 'Santa Fe', runnerUpName: 'Huracan', finalScore: '0-0 (3-1 pen.)', venue: 'Bogota, Colombia' },
    { season: '2014', championName: 'River Plate', runnerUpName: 'Atletico Nacional', finalScore: '3-1 agg.', venue: null },
    { season: '2013', championName: 'Lanus', runnerUpName: 'Ponte Preta', finalScore: '3-1 agg.', venue: null },
    { season: '2012', championName: 'Sao Paulo', runnerUpName: 'Tigre', finalScore: '2-0 agg.', venue: null },
    { season: '2011', championName: 'Universidad de Chile', runnerUpName: 'Liga de Quito', finalScore: '4-0 agg.', venue: null },
    { season: '2010', championName: 'Independiente', runnerUpName: 'Goias', finalScore: '3-3 (5-3 pen.)', venue: null },
    { season: '2009', championName: 'Liga de Quito', runnerUpName: 'Fluminense', finalScore: '5-4 agg.', venue: null },
    { season: '2008', championName: 'Internacional', runnerUpName: 'Estudiantes', finalScore: '2-1 agg.', venue: null },
    { season: '2007', championName: 'Arsenal', runnerUpName: 'America', finalScore: '4-4 agg. (away goals)', venue: null },
    { season: '2006', championName: 'Pachuca', runnerUpName: 'Colo-Colo', finalScore: '3-2 agg.', venue: null },
    { season: '2005', championName: 'Boca Juniors', runnerUpName: 'UNAM', finalScore: '2-2 (4-3 pen.)', venue: null },
    { season: '2004', championName: 'Boca Juniors', runnerUpName: 'Bolivar', finalScore: '2-1 agg.', venue: null },
    { season: '2003', championName: 'Cienciano', runnerUpName: 'River Plate', finalScore: '4-3 agg.', venue: null },
    { season: '2002', championName: 'San Lorenzo', runnerUpName: 'Atletico Nacional', finalScore: '4-0 agg.', venue: null },
  ],
  'internacional-champions': [
    { season: '2025/26', championName: 'Paris Saint Germain', runnerUpName: 'Arsenal', finalScore: '1-1 (4-3 pen.)', venue: 'Budapest, Hungría' },
    { season: '2024/25', championName: 'Paris Saint Germain', runnerUpName: 'Inter', finalScore: '5-0', venue: 'Múnich, Alemania' },
    { season: '2023/24', championName: 'Real Madrid', runnerUpName: 'Borussia Dortmund', finalScore: '2-0', venue: 'Londres, Inglaterra' },
    { season: '2022/23', championName: 'Manchester City', runnerUpName: 'Inter', finalScore: '1-0', venue: 'Estambul, Turquía' },
    { season: '2021/22', championName: 'Real Madrid', runnerUpName: 'Liverpool', finalScore: '1-0', venue: 'Saint-Denis, Francia' },
    { season: '2020/21', championName: 'Chelsea', runnerUpName: 'Manchester City', finalScore: '1-0', venue: 'Porto, Portugal' },
    { season: '2019/20', championName: 'Bayern Munchen', runnerUpName: 'Paris Saint Germain', finalScore: '1-0', venue: 'Lisboa, Portugal' },
    { season: '2018/19', championName: 'Liverpool', runnerUpName: 'Tottenham Hotspur', finalScore: '2-0', venue: 'Madrid, España' },
    { season: '2017/18', championName: 'Real Madrid', runnerUpName: 'Liverpool', finalScore: '3-1', venue: 'Kiev, Ucrania' },
    { season: '2016/17', championName: 'Real Madrid', runnerUpName: 'Juventus', finalScore: '4-1', venue: 'Cardiff, Gales' },
    { season: '2015/16', championName: 'Real Madrid', runnerUpName: 'Atletico de Madrid', finalScore: '1-1 (5-3 pen.)', venue: 'Milan, Italia' },
    { season: '2014/15', championName: 'Barcelona', runnerUpName: 'Juventus', finalScore: '3-1', venue: 'Berlín, Alemania' },
  ],
  'internacional-europa-league': [
    { season: '2024/25', championName: 'Tottenham Hotspur', runnerUpName: 'Manchester United', finalScore: '1-0', venue: 'Bilbao, España' },
    { season: '2023/24', championName: 'Atalanta', runnerUpName: 'Bayer Leverkusen', finalScore: '3-0', venue: 'Dublin, Irlanda' },
    { season: '2022/23', championName: 'Sevilla', runnerUpName: 'Roma', finalScore: '1-1 (4-1 pen.)', venue: 'Budapest, Hungría' },
    { season: '2021/22', championName: 'Eintracht Frankfurt', runnerUpName: 'Rangers', finalScore: '1-1 (5-4 pen.)', venue: 'Sevilla, España' },
    { season: '2020/21', championName: 'Villarreal', runnerUpName: 'Manchester United', finalScore: '1-1 (11-10 pen.)', venue: 'Gdansk, Polonia' },
    { season: '2019/20', championName: 'Sevilla', runnerUpName: 'Inter', finalScore: '3-2', venue: 'Colonia, Alemania' },
    { season: '2018/19', championName: 'Chelsea', runnerUpName: 'Arsenal', finalScore: '4-1', venue: 'Baku, Azerbaiyán' },
    { season: '2017/18', championName: 'Atletico de Madrid', runnerUpName: 'Olympique de Marseille', finalScore: '3-0', venue: 'Lyon, Francia' },
    { season: '2016/17', championName: 'Manchester United', runnerUpName: 'Ajax', finalScore: '2-0', venue: 'Estocolmo, Suecia' },
    { season: '2015/16', championName: 'Sevilla', runnerUpName: 'Liverpool', finalScore: '3-1', venue: 'Basilea, Suiza' },
    { season: '2014/15', championName: 'Sevilla', runnerUpName: 'Dnipro', finalScore: '3-2', venue: 'Varsovia, Polonia' },
  ],
} as const
