export const ADSENSE_PUBLISHER_ID =
  process.env.NEXT_PUBLIC_ADSENSE_PUBLISHER_ID || 'ca-pub-9918770947892784'

export const ADSENSE_DISPLAY_SLOT_ID = process.env.NEXT_PUBLIC_ADSENSE_DISPLAY_SLOT_ID
